apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
    name: master
spec:
  containers:
   -  name: master
      image: robopaas/rosmaster:latest
      ports:
        - containerPort: 11311
          name: master
      args:
          - roscore
